# Trực quan hóa dữ liệu – Lab 02
## Khai thác và trực quan hóa dữ liệu World Development Indicators (WDI)
**GVHD:** Võ Nhật Tân  
**Nhóm:** [MSSV_1, MSSV_2, MSSV_3]  
**Ngày:** 25/03/2026
---

In [1]:
# Cài đặt thư viện
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 11
sns.set_style('whitegrid')

In [2]:
# Đường dẫn dataset
import os
DATA_PATH = '/home/nesfan/Desktop/HCMUS/Nam3/HK2/TQH/Lab2/data/dataset.csv'

## 1. Phân tích cơ bản về dữ liệu

---

### 1.1 Giới thiệu tổng quan về dataset

**World Development Indicators (WDI)** là bộ dữ liệu do Ngân hàng Thế giới (World Bank) cung cấp, bao gồm hơn 1.600 chỉ số về kinh tế, xã hội và môi trường của hơn 200 quốc gia trên toàn cầu.

Dataset trong bài phân tích này bao gồm các chỉ số phát triển của **Việt Nam (VNM)** từ năm 2001 đến 2025, bao gồm:
- **Tỷ lệ nhập học đại học (% gross)** – SE.TER.ENRR
- **Tỷ lệ thất nghiệp (% of total labor force, modeled ILO)** – SL.UEM.TOTL.ZS
- **Tỷ lệ lao động trong ngành dịch vụ (% of total employment, modeled ILO)** – SL.SRV.EMPL.ZS

In [4]:
# Đọc dữ liệu
df_raw = pd.read_csv(DATA_PATH)

print(f"Kích thước ban đầu: {df_raw.shape[0]} dòng × {df_raw.shape[1]} cột")
print(f"\nTên các cột:\n{list(df_raw.columns)}")

Kích thước ban đầu: 8 dòng × 29 cột

Tên các cột:
['Country Name', 'Country Code', 'Series Name', 'Series Code', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]', '2024 [YR2024]', '2025 [YR2025]']

### 1.2 Cấu trúc dữ liệu

**Bản ghi (rows):** Mỗi dòng tương ứng với một chỉ số (metric) của Việt Nam qua các năm.  
**Trường dữ liệu (columns):**
| Trường | Mô tả |
|---|---|
| `Country Name` | Tên quốc gia |
| `Country Code` | Mã quốc gia (ISO 3-letter) |
| `Series Name` | Tên chỉ số |
| `Series Code` | Mã chỉ số |
| `2001 [YR2001] … 2025 [YR2025]` | Giá trị chỉ số theo từng năm |

In [5]:
# Xem toàn bộ dữ liệu gốc
df_raw.head(10)

,Country Name,Country Code,Series Name,Series Code,2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Viet Nam,VNM,"School enrollment, tertiary (% gross)",SE.TER.ENRR,9.301030,9.557230,9.917930,..,15.876020,16.805250,...,29.081198,25.952631,..,30.224119,..,41.955497,44.753685,32.841513,37.592364,..
1,Viet Nam,VNM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2.760000,2.120000,2.250000,2.14,2.078000,2.046000,...,1.848000,1.874000,1.161,1.681000,2.103,2.383000,1.570000,1.645000,1.602000,1.523
2,Viet Nam,VNM,Employment in services (% of total employment)...,SL.SRV.EMPL.ZS,23.542105,24.747927,25.446588,26.3436096365078,28.064612,29.900225,...,33.372888,34.067720,35.5711648258268,35.875656,36.3177224262355,37.846094,35.855035,39.549416,39.806349,40.1305077279733
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Last Updated: 02/24/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Kiểu dữ liệu từng cột
print("Kiểu dữ liệu từng cột:")
print(df_raw.dtypes)

Kiểu dữ liệu từng cột:
Country Name         str
Country Code         str
Series Name          str
Series Code          str
2001 [YR2001]    float64
2002 [YR2002]    float64
2003 [YR2003]    float64
2004 [YR2004]        str
2005 [YR2005]    float64
2006 [YR2006]    float64
2007 [YR2007]    float64
2008 [YR2008]    float64
2009 [YR2009]    float64
2010 [YR2010]    float64
2011 [YR2011]    float64
2012 [YR2012]    float64
2013 [YR2013]    float64
2014 [YR2014]    float64
2015 [YR2015]    float64
2016 [YR2016]    float64
2017 [YR2017]    float64
2018 [YR2018]        str
2019 [YR2019]    float64
2020 [YR2020]        str
2021 [YR2021]    float64
2022 [YR2022]    float64
2023 [YR2023]    float64
2024 [YR2024]    float64
2025 [YR2025]        str
dtype: object

In [13]:
# Làm sạch: loại bỏ dòng footer / dòng trống
# Chỉ giữ dòng có Country Name và Series Name hợp lệ
df = df_raw[
    df_raw['Country Name'].notna() &
    (df_raw['Country Name'].str.strip() != '') &
    df_raw['Series Name'].notna() &
    (df_raw['Series Name'].astype(str).str.strip() != '') &
    (df_raw['Series Name'].astype(str) != 'nan')
].copy().reset_index(drop=True)

print("\nCác dòng bị loại (gồm footer và dòng trống):")
removed_idx = set(df_raw.index) - set(df.index)
for idx in removed_idx:
    row = df_raw.loc[idx]
    print(f"  Dòng {idx}: Country='{row['Country Name']}', Series='{row['Series Name']}'")

Các dòng bị loại (gồm footer và dòng trống):
  Dòng 3: Country='nan', Series='nan'
  Dòng 4: Country='nan', Series='nan'
  Dòng 5: Country='nan', Series='nan'
  Dòng 6: Country='Data from database: World Development Indicators', Series='nan'
  Dòng 7: Country='Last Updated: 02/24/2026', Series='nan'

### 1.3 Phân tích thống kê mô tả

Thống kê mô tả cho các giá trị số (các năm từ 2001–2025) bao gồm: count, mean, std, min, max, và các phân vị (25%, 50%, 75%).

In [14]:
# Lấy danh sách cột năm
year_cols = [c for c in df.columns if c.startswith('20')]
print(f"Số năm có dữ liệu: {len(year_cols)} (từ {year_cols[0]} đến {year_cols[-1]})")

# Chuyển sang numeric
df_years = df[year_cols].apply(pd.to_numeric, errors='coerce')
print(f"\nThống kê mô tả:\n{df_years.describe().round(3)}")

Số năm có dữ liệu: 25 (từ 2001 [YR2001] đến 2025 [YR2025])

Thống kê mô tả:
       2001 [YR2001]  2002 [YR2002]  2003 [YR2003]  2004 [YR2004]  \
count          3.000          3.000          3.000          2.000
mean          11.868         12.142         12.538         14.242
std           10.626         11.533         11.818         17.115
min            2.760          2.120          2.250          2.140
25%            6.031          5.839          6.084          8.191
50%            9.301          9.557          9.918         14.242
75%           16.422         17.153         17.682         20.293
max           23.542         24.748         25.447         26.344

       2005 [YR2005]  2006 [YR2006]  2007 [YR2007]  2008 [YR2008]  \
count          3.000          3.000          3.000          3.000
mean          15.340         16.250         17.102         17.451
std           13.002         13.935         14.241         14.437
min            2.078          2.046          2.026          1.889
25%            8.977          9.426         10.488         10.972
50%           15.876         16.805         18.950         20.055
75%           21.970         23.353         24.639         25.232
max           28.065         29.900         30.328         30.409

       2009 [YR2009]  2010 [YR2010]  ...  2016 [YR2016]  2017 [YR2017]  \
count          3.000          3.000  ...          3.000          3.000
mean          17.946         18.218  ...         21.434         20.631
std           14.756         15.083  ...         17.097         16.744
min            1.737          1.114  ...          1.848          1.874
25%           11.619         12.520  ...         15.465         13.913
50%           21.501         23.925  ...         29.081         25.953
75%           26.050         26.770  ...         31.227         30.010
max           30.599         29.614  ...         33.373         34.068

       2018 [YR2018]  2019 [YR2019]  2020 [YR2020]  2021 [YR2021]  \
count          2.000          3.000          2.000          3.000
mean          18.366         22.594         19.210         27.395
std           24.332         18.330         24.193         21.758
min            1.161          1.681          2.103          2.383
25%            9.764         15.953         10.657         20.115
50%           18.366         30.224         19.210         37.846
75%           26.969         33.050         27.764         39.901
max           35.571         35.876         36.318         41.955

       2022 [YR2022]  2023 [YR2023]  2024 [YR2024]  2025 [YR2025]
count          3.000          3.000          3.000          2.000
mean          27.393         24.679         26.334         20.827
std           22.802         20.228         21.447         27.300
min            1.570          1.645          1.602          1.523
25%           18.713         17.243         19.597         11.175
50%           35.855         32.842         37.592         20.827
75%           40.304         36.195         38.699         30.479
max           44.754         39.549         39.806         40.131

[8 rows x 25 columns]

In [15]:
# Thống kê chi tiết từng chỉ số
for i, row in df.iterrows():
    vals = pd.to_numeric(row[year_cols], errors='coerce')
    print(f"   Series Code : {row['Series Code']}")
    print(f"   Count  : {vals.count()} / {len(year_cols)} năm có dữ liệu")
    print(f"   Mean   : {vals.mean():.4f}")
    print(f"   Std    : {vals.std():.4f}")
    print(f"   Min    : {vals.min():.4f}")
    print(f"   Max    : {vals.max():.4f}")
    print(f"   25%    : {vals.quantile(0.25):.4f}")
    print(f"   50%    : {vals.quantile(0.50):.4f}")
    print(f"   75%    : {vals.quantile(0.75):.4f}")

   Series Code : SE.TER.ENRR
   Count  : 21 / 25 năm có dữ liệu
   Mean   : 25.0756
   Std    : 9.8586
   Min    : 9.3010
   Max    : 44.7537
   25%    : 18.9505
   50%    : 25.7487
   75%    : 30.2241
   Series Code : SL.UEM.TOTL.ZS
   Count  : 25 / 25 năm có dữ liệu
   Mean   : 1.7598
   Std    : 0.4472
   Min    : 0.9990
   Max    : 2.7600
   25%    : 1.5230
   50%    : 1.8480
   75%    : 2.0780
   Series Code : SL.SRV.EMPL.ZS
   Count  : 25 / 25 năm có dữ liệu
   Mean   : 32.2681
   Std    : 4.6557
   Min    : 23.5421
   Max    : 40.1305
   25%    : 29.9002
   50%    : 32.0034
   75%    : 35.8550

### 1.4 Tỷ lệ giá trị thiếu (% Missing Values) – Trước khi Imputation

In [22]:
# ── % Missing Values – TRƯỚC IMPUTATION ──
total_cells = df_years.size           # dòng × năm
total_missing = df_years.isnull().sum().sum()
overall_pct = round(total_missing / total_cells * 100, 2)

print(f"\nTổng quan:")
print(f"   Tổng số ô dữ liệu : {total_cells}")
print(f"   Số ô bị thiếu     : {total_missing}")
print(f"   Tỷ lệ thiếu       : {overall_pct}%")

# Theo từng CHỈ SỐ (dòng)
missing_per_row  = df_years.isnull().sum(axis=1)
pct_per_row      = (missing_per_row / len(year_cols) * 100).round(2)

# Theo từng NĂM (cột)
missing_per_col  = df_years.isnull().sum()
pct_per_col      = (missing_per_col / len(df_years) * 100).round(2)

print(f"\nTheo từng CHỈ SỐ (dòng):")
for i, row in df.iterrows():
    n = missing_per_row.iloc[i]
    p = pct_per_row.iloc[i]
    short_name = str(row['Series Name'])[:60]
    print(f"   {short_name} ... | Thiếu: {n}/{len(year_cols)} năm ({p}%)")

print(f"\nTheo từng NĂM (cột):")
for col, n, p in zip(year_cols, missing_per_col, pct_per_col):
    bar = " " * int(p // 5) if p > 0 else ""
    print(f"   {col} | Thiếu: {n}/{len(df_years)} chỉ số ({p}%) {bar}")

Tổng quan:
   Tổng số ô dữ liệu : 75
   Số ô bị thiếu     : 4
   Tỷ lệ thiếu       : 5.33%

Theo từng CHỈ SỐ (dòng):
   School enrollment, tertiary (% gross) ... | Thiếu: 4/25 năm (16.0%)
   Unemployment, total (% of total labor force) (modeled ILO es ... | Thiếu: 0/25 năm (0.0%)
   Employment in services (% of total employment) (modeled ILO  ... | Thiếu: 0/25 năm (0.0%)

Theo từng NĂM (cột):
   2001 [YR2001] | Thiếu: 0/3 chỉ số (0.0%)
   2002 [YR2002] | Thiếu: 0/3 chỉ số (0.0%)
   2003 [YR2003] | Thiếu: 0/3 chỉ số (0.0%)
   2004 [YR2004] | Thiếu: 1/3 chỉ số (33.33%)
   2005 [YR2005] | Thiếu: 0/3 chỉ số (0.0%)
   2006 [YR2006] | Thiếu: 0/3 chỉ số (0.0%)
   2007 [YR2007] | Thiếu: 0/3 chỉ số (0.0%)
   2008 [YR2008] | Thiếu: 0/3 chỉ số (0.0%)
   2009 [YR2009] | Thiếu: 0/3 chỉ số (0.0%)
   2010 [YR2010] | Thiếu: 0/3 chỉ số (0.0%)
   2011 [YR2011] | Thiếu: 0/3 chỉ số (0.0%)
   2012 [YR2012] | Thiếu: 0/3 chỉ số (0.0%)
   2013 [YR2013] | Thiếu: 0/3 chỉ số (0.0%)
   2014 [YR2014] | Thiếu: 0/3 chỉ số (0.0%)
   2015 [YR2015] | Thiếu: 0/3 chỉ số (0.0%)
   2016 [YR2016] | Thiếu: 0/3 chỉ số (0.0%)
   2017 [YR2017] | Thiếu: 0/3 chỉ số (0.0%)
   2018 [YR2018] | Thiếu: 1/3 chỉ số (33.33%)
   2019 [YR2019] | Thiếu: 0/3 chỉ số (0.0%)
   2020 [YR2020] | Thiếu: 1/3 chỉ số (33.33%)
   2021 [YR2021] | Thiếu: 0/3 chỉ số (0.0%)
   2022 [YR2022] | Thiếu: 0/3 chỉ số (0.0%)
   2023 [YR2023] | Thiếu: 0/3 chỉ số (0.0%)
   2024 [YR2024] | Thiếu: 0/3 chỉ số (0.0%)
   2025 [YR2025] | Thiếu: 1/3 chỉ số (33.33%)

### 1.5 Tiền xử lý dữ liệu

#### 1.5.1 Xử lý giá trị thiếu (Imputation)

Vì đây là dữ liệu chuỗi thời gian (time-series), ta sử dụng **Linear Interpolation** để điền khuyết, phù hợp với xu hướng dài hạn của các chỉ số phát triển.

In [23]:
# --- Buoc 1: Parse tat ca cot nam sang float truoc ---
df_clean = df.copy().reset_index(drop=True)
year_cols = [c for c in df_clean.columns if c.startswith('20')]

# Chuyen '..' va chuoi rac -> NaN, ep kieu float
for col in year_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

print("Kieu du lieu cac cot nam sau parse:")
print(df_clean[year_cols].dtypes.value_counts())

# --- Buoc 2: Linear Interpolation cho tung chi so ---
for i in range(len(df_clean)):
    vals = df_clean.loc[i, year_cols].astype(float)
    interp = vals.interpolate(method='linear', limit_direction='both')
    interp = interp.ffill().bfill()   # dau/cuoi con thieu
    df_clean.loc[i, year_cols] = interp.values

# Verify
df_check = df_clean[year_cols].apply(pd.to_numeric, errors='coerce')
print(f"\nKiem tra sau imputation: {df_check.isnull().sum().sum()} o con thieu")

Kieu du lieu cac cot nam sau parse:
float64    25
Name: count, dtype: int64

Kiem tra sau imputation: 0 o con thieu

In [25]:
# Dataset sau tiền xử lý
print("Dataset sau tiền xử lý:\n")
df_clean[['Country Name', 'Country Code', 'Series Name', 'Series Code']].head(3)

Dataset sau tiền xử lý:

,Country Name,Country Code,Series Name,Series Code
0,Viet Nam,VNM,"School enrollment, tertiary (% gross)",SE.TER.ENRR
1,Viet Nam,VNM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS
2,Viet Nam,VNM,Employment in services (% of total employment)...,SL.SRV.EMPL.ZS